/* Auth Types */
export const ADD_NAME = 'ADD_NAME';
export const ADD_EMAIL = 'ADD_EMAIL';
export const ADD_PASSWORD = 'ADD_PASSWORD';
export const ADD_CONFIRM_PASSWORD = 'ADD_CONFIRM_PASSWORD';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const SUCCESS_REGISTER = 'SUCCESS_REGISTER';
export const FAILURE_REGISTER = 'FAILURE_REGISTER';
export const SIGN_IN_LOADING = 'SIGN_IN_LOADING';
export const SIGN_UP_LOADING = 'SIGN_UP_LOADING';
export const SAVE_USER = 'SAVE_USER';

/* Application Types */
export const ADD_CONTACT = 'ADD_CONTACT';
export const ADD_NEW_CONTACT_ERROR = 'ADD_NEW_CONTACT_ERROR';
export const ADD_NEW_CONTACT_SUCCESS = 'ADD_NEW_CONTACT_SUCCESS';
export const FAILED_LOAD_CONTACTS = 'FAILED_LOAD_CONTACTS';
export const LOADING_CONTACTS = 'LOADING_CONTACTS';
export const LOADING_ADD_CONTACTS_TO_TRIP = 'LOADING_ADD_CONTACTS_TO_TRIP';
export const FAILED_TO_ADD_CONTACT_TO_TRIP = 'FAILED_TO_ADD_CONTACT_TO_TRIP';

export const CONTACTS_LIST = 'CONTACTS_LIST';
export const CHANGE_MESSAGE = 'CHANGE_MESSAGE';
export const FETCH_ALL_CHATS = 'FETCH_ALL_CHATS';
export const FETCH_ONE_CHAT = 'FETCH_ON_CHAT';
export const FETCH_NEW_CHAT_LIST = 'FETCH_NEW_CHAT_LIST';
export const CLEAR_CONTACT_CHATS = 'CLEAR_CONTACT_CHATS';
export const CLEAR_ALL_CONVERSATIONS = 'CLEAR_ALL_CONVERSATIONS';
// export const FETCH_UNREAD_CHAT_COUNT = 'FETCH_UNREAD_CHAT_COUNT';
export const UPDATE_CHAT_LIST = 'UPDATE_CHAT_LIST';
export const CONTACT_IS_SELECTED = 'CONTACT_IS_SELECTED';
export const UNSELECT_ALL_CONTACTS = 'UNSELECT_ALL_CONTACTS';
export const ADD_CONTACTS_TO_TRIP = 'ADD_CONTACTS_TO_TRIP';
// export const MARK_CHATS_AS_READ = 'MARK_CHATS_AS_READ';
export const INCREASE_UNREAD_COUNT = 'INCREASE_UNREAD_COUNT';
export const SET_UNREAD_COUNT = 'SET_UNREAD_COUNT';

// Participants
export const FAILED_LOAD_PARTICIPANTS = 'FAILED_LOAD_PARTICIPANTS';
export const PARTICIPANTS_LIST = 'PARTICIPANTS_LIST';
export const LOADING_PARTICIPANTS = 'LOADING_PARTICIPANTS';
export const PARTICIPANT_IS_SELECTED = 'PARTICIPANT_IS_SELECTED';
export const UNSELECT_ALL_PARTICIPANTS = 'UNSELECT_ALL_PARTICIPANTS';
export const UPDATE_PARTICIPANT_PERMISSIONS = 'UPDATE_PARTICIPANT_PERMISSIONS'; // update permissions

export const LIST_CONVERSATION_USER = 'LIST_CONVERSATION_USER';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';

// Trips
export const ADD_TRIP = 'ADD_TRIP';
export const ADD_TRIPS = 'ADD_TRIPS';
export const TRIPS_LOADING = 'TRIPS_LOADING';
export const TRIP_LOADING = 'TRIP_LOADING';
export const UPDATE_TRIP = 'UPDATE_TRIP';
export const TRIP_ITINERARY__LOADING = 'TRIP_ITINERARY__LOADING';
export const LOADING_TRIP_ITINERARY_BTN = 'LOADING_TRIP_ITINERARY_BTN';
export const SHOW_MODIFY_ITINERARY_MODAL = 'SHOW_MODIFY_ITINERARY_MODAL';
export const ADD_COPY_OF_TRIP_ITINERARY = 'ADD_COPY_OF_TRIP_ITINERARY';
export const FAIL_LOAD_TRIP = 'FAIL_LOAD_TRIP';
export const HIGHLIGHT_MODE = 'HIGHLIGHT_MODE';
export const FAILED_TO_LOAD_TRIPS = 'FAILED_TO_LOAD_TRIPS';
export const PREPEND_TRIP_TO_TRIPS = 'PREPEND_TRIP_TO_TRIPS';
export const USER_TRIP_PERMISSIONS = 'USER_TRIP_PERMISSIONS';
export const USER_TRIP_SUB_PERMISSIONS = 'USER_TRIP_SUB_PERMISSIONS';
export const UPDATE_TRIP_EMERGENCY_CONTACTS = 'UPDATE_TRIP_EMERGENCY_CONTACTS';
//resets
export const RESET_TRIPS = 'RESET_TRIPS';
export const RESET_LIST_CHATS = 'RESET_LIST_CHATS';
export const RESET_CONTACTS = 'RESET_CONTACTS';

//ListConversation
export const ADD_USER_CONVERSATIONS = 'ADD_USER_CONVERSATIONS';
export const SET_CONVERSATIONS = 'SET_CONVERSATIONS';
export const RESET_USER_CONVERSATION = 'RESET_USER_CONVERSATION';
export const ADD_ONE_MESSAGE = 'ADD_ONE_MESSAGE';
export const UPDATE_ONE_MESSAGE = 'UPDATE_ONE_MESSAGE';
export const UPDATE_A_MESSAGE = 'UPDATE_A_MESSAGE';
export const RESET_CHATLIST_UNREAD = 'RESET_CHATLIST_UNREAD';
// export const ADD_LISTENER_DETAILS = 'ADD_LISTENER_DETAILS';
// export const OFF_ONE_LISTENER_DETAIL = 'OFF_ONE_LISTENER_DETAIL';
// export const OFF_ALL_LISTENERS = 'OFF_ALL_LISTENERS';
// export const SHOW_MODIFY_TRIP_ITINERARY = 'SHOW_MODIFY_TRIP_ITINERARY'
// showModifyItinerary

//Broadcast chats
export const ADD_BROADCAST_MESSAGES = 'ADD_BROADCAST_MESSAGES';
export const ADD_BROADCAST_MESSAGE = 'ADD_BROADCAST_MESSAGE';
export const RESET_BROADCAST_CHATS = 'RESET_BROADCAST_CHATS';
export const LAST_BROADCAST_MESSAGE = 'LAST_BROADCAST_MESSAGE';
export const PREPEND_MESSAGES_TO_BROADCAST = 'PREPEND_MESSAGES_TO_BROADCAST';
//Chapperones chats
export const ADD_CHAPPERONES_MESSAGES = 'ADD_CHAPPERONES_MESSAGES';
export const ADD_CHAPPERONES_MESSAGE = 'ADD_CHAPPERONES_MESSAGE';
export const RESET_CHAPPERONES_CHATS = 'RESET_CHAPPERONES_CHATS';
export const LAST_CHAPPERONES_MESSAGE = 'LAST_CHAPPERONES_MESSAGE';
export const APPEND_CHAPPERONES_MESSAGES = 'APPEND_CHAPPERONES_MESSAGES';
export const UPDATE_GROUP_MESSAGE = 'UPDATE_GROUP_MESSAGE';
// Notification indicators
export const CHANGE_UNREAD_MESSAGE_STATUS = 'CHANGE_UNREAD_MESSAGE_STATUS';
export const CHANGE_UNREAD_BROADCAST_STATUS = 'CHANGE_UNREAD_BROADCAST_STATUS';
export const RESET_NOTIFICATION_INDICATOR = 'RESET_NOTIFICATION_INDICATOR';
export const CHANGE_UNREAD_TRIP_BROADCAST_STATUS =
  'CHANGE_UNREAD_TRIP_BROADCAST_STATUS';
